theme: jekyll-theme-slate

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Alucebur Was Here"
      description: "I will be posting here different stuff about my projects"
