theme: jekyll-theme-slate
title: "Alucebur Was Here"
description: "I will be posting here different stuff about my projects"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:categories/:title:output_ext
      layout: post
